### PR TITLE
Allow auth on non-public surveys

### PR DESCRIPTION
**Pull request by AndrewPoppe**
Adds system-level setting to enable the EM to apply to both public and non-public surveys.

See issue #6

### CODE REVIEW

**Comment by AndrewPoppe** [comment]
Apologies, I should have tested more thoroughly. I think I will need to take a closer look at how this might work. Currently with my PR it creates an infinite loop when trying to authenticate on a non-public survey.

**Comment by AndrewPoppe** [comment]
New commit adds non-public functionality. But I made many changes, as you'll see. If you are uneasy incorporating these, let me know and I'll just maintain a fork.

**Comment by grezniczek** [comment]
@AndrewPoppe 
Whoops, I only now saw this PR. Somehow GitHub faild to notify me. Sorry about that.
I will have a look at this soon.

**Comment by grezniczek** [comment]
@AndrewPoppe , I had a look at this now. I found it to not working as intended in a number of circumstances, e.g. when surveys have multiple pages. Furthermore, nothing could be written to the (first) survey page by the module, as any values would be overwritten once the survey page was submitted.

However, I think this is a very useful addition and have integrated this feature. You'll find part of your code in this [branch](https://github.com/grezniczek/redcap_survey_auth/tree/non-public-auth).

I'd like to name you as **co-author** in the module (config.json entry), if you are ok with this?  In fact, I already did, but please give me your ok (please check if the details are correct, I took them from GitHub).
I'd like to release this as soon as possible.

**Comment by AndrewPoppe** [comment]
Sure, that works for me. I'm glad you were able to get it working!

**Comment by AndrewPoppe** [comment]
Actually, could you use this email instead: andrew.poppe@yale.edu

Thanks!

**Comment by grezniczek** [comment]
Done :)

**Pull request closed without merging**
