### PR TITLE
Allow @IF evaluation of @SURVEY-AUTH action tag

### PR DESCRIPTION
**Pull request by AndrewPoppe**
This leverages REDCap's `@IF` action tag to provide flexibility on whether the module enforces authentication or not. For example, suppose a user wants to authenticate a non-public survey only if the respondent provided a certain response on the previous public survey.

Instead of detecting whether the `@SURVEY-AUTH` tag exists at all in a field's annotation, it parses any `@IF` tags to determine whether the `@SURVEY-AUTH` tag should be active or not.

Caveats:

1. It calls REDCap's internal methods for parsing `@IF` tags. This seems better than attempting to roll our own, but would require monitoring to ensure the arguments and output of the internal methods do not change.
2. If `$record` is null in the `redcap_survey_page_top` hook (e.g., a public survey), this assigns a value of '1'. This is required to make the `@IF` evaluation work correctly, as passing `null` to REDCap's internal method did not work correctly.

### CODE REVIEW

**Comment by grezniczek** [comment]
@AndrewPoppe, thanks for this.

However, this failed on my dev machine, leading to the login check being bypassed entirely, because `Form::replaceIfActionTag()` would sometimes falsely remove the `@SURVEY-AUTH`.

It took me a while to find the issue ... which lies in `Form::evaluateIfActionTag()`, where the outcome depends on a global variable. 
```php
// If record doesn't exist yet, then submit empty array of redcap_data
$record_data = null;
if ($GLOBALS['hidden_edit'] == 0) {
    $record_data = [" "=>Records::getDefaultValues($project_id)];
}
```

I also ensured that `$record` would always have a value if it should have one.

`@IF` is only supported on non-public surveys, as there is no record (and therefore no data) that would be useful for a conditional logic (except maybe aggregate functions, but ... no ;).

**Comment by AndrewPoppe** [comment]
Interesting, I had assumed that `@IF` would be supported on public surveys as some smart variables that don't depend on the record existing might still be useful in the condition, but that's what I get for assuming! 

I'll have to figure something else out for my use case - I want two arms to use the same public survey but only one arm be required to authenticate. I hoped to use an `@IF` with an `[arm-number]` condition. 

Anyway, thanks for figuring that out!

**Comment by grezniczek** [comment]
Hm, I guess my thinking was too limited in figuring "no record, no point of any IFs". I had overlooked those smart variables you mention.
The decision to "keep as is" for public surveys was arbitrary, and is not something that needs to be. Thus, I will change this now.

**Comment by grezniczek** [comment]
@AndrewPoppe, I just made a new release. I see why you needed to set $record to "1" to get action tag evaluation to work. It's all a bit hacky because the REDCap code is quite hacky, too.

**Comment by AndrewPoppe** [comment]
@grezniczek Great, thanks for that! I'll test the new release now in my dev environment.

**Comment by AndrewPoppe** [comment]
@grezniczek Hm I think I'm encountering a couple bugs (not authenticating in `@IF` in non-public survey, not forwarding to the survey after successful authentication on public survey), but I will have to wait until later this afternoon to investigate. 

Just to be sure, should I be testing the latest release (v1.4.1) or the current master branch?

**Comment by grezniczek** [comment]
@AndrewPoppe, found the issue.

Please test against master. I will hold off on releasing this time around ....

**Comment by AndrewPoppe** [comment]
🤦‍♂️ I reinstalled the EM and neglected to allow authentication on non-public surveys in the system config... 

I'll go ahead and test now.

**Comment by grezniczek** [comment]
I wonder if this setting should be removed. With `@IF` support, "turning off" could be easily achieved.

**Comment by grezniczek** [comment]
See #11

**Comment by grezniczek** [comment]
@AndrewPoppe , thanks for the projects and this excellent test roster!

All tests should pass now.

**Comment by AndrewPoppe** [comment]
@grezniczek Indeed, all tests pass! I'm sorry this turned into such an involved affair; I really thought my tiny PR was going to do the trick 😂

**Comment by grezniczek** [comment]
@AndrewPoppe , no worries.
The module is much improved now! Well worth it, I think.

**Pull request merged**
